### list todos
GET http://localhost:3000/todos

### get todo
GET http://localhost:3000/todos/dfd985ab-92a9-4cd5-af07-f1e553d6b06b

### create todo
POST http://localhost:3000/todos
Content-Type: application/json

{
    "title": "Task 1",
    "body": "Description of task 1",
    "state": "TODO",
    "categoryId": 1,
    "createdAt": "2024-09-04"
}

### update todo
PATCH http://localhost:3000/todos/dfd985ab-92a9-4cd5-af07-f1e553d6b06b
Content-Type: application/json

{
    "body": "new description to task 1"
}

### delete todo
DELETE http://localhost:3000/todos/dfd985ab-92a9-4cd5-af07-f1e553d6b06b