### list todos
GET http://localhost:3000/todos

### get todo
GET http://localhost:3000/todos/a3720ed5-e1a1-4a96-a47e-cf6ee6d7f7b1

### create todo
POST http://localhost:3000/todos
Content-Type: application/json

{
    "title": "Task 1",
    "body": "Description of task 1",
    "state": "TODO",
    "categoryId": 1,
    "createdAt": "2024-09-04"
}

### update todo
PATCH http://localhost:3000/todos/a3720ed5-e1a1-4a96-a47e-cf6ee6d7f7b1
Content-Type: application/json

{
    "body": "new description to task 1"
}

### delete todo
DELETE http://localhost:3000/todos/a3720ed5-e1a1-4a96-a47e-cf6ee6d7f7b1